<?php

namespace AppBundle\Repository;

/**
 * CaducidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaducidadRepository extends \Doctrine\ORM\EntityRepository
{
}
