<?php

namespace AppBundle\Repository;

/**
 * ChequeTerceroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChequeTerceroRepository extends \Doctrine\ORM\EntityRepository
{
}
