<?php

namespace AppBundle\Repository;

/**
 * ChequeraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChequeraRepository extends \Doctrine\ORM\EntityRepository
{
}
