<?php

namespace AppBundle\Repository;

/**
 * ChequePropioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChequePropioRepository extends \Doctrine\ORM\EntityRepository
{
}
