<?php

namespace AppBundle\Repository;

/**
 * ComprobanteProveedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComprobanteProveedorRepository extends \Doctrine\ORM\EntityRepository
{
}
