<?php

namespace AppBundle\Repository;

/**
 * ContratistaRubroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratistaRubroRepository extends \Doctrine\ORM\EntityRepository
{
}
