<?php

namespace AppBundle\Repository;

/**
 * ContactoAlternativoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactoAlternativoRepository extends \Doctrine\ORM\EntityRepository
{
}
