<?php

namespace AppBundle\Repository;

/**
 * ContratistaObraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContratistaObraRepository extends \Doctrine\ORM\EntityRepository
{
}
