<?php

namespace AppBundle\Repository;

/**
 * DetallePedidoOrdenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetallePedidoOrdenRepository extends \Doctrine\ORM\EntityRepository
{
}
