<?php

namespace AppBundle\Repository;

/**
 * DetalleOrdenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleOrdenRepository extends \Doctrine\ORM\EntityRepository
{
}
