<?php

namespace AppBundle\Repository;

/**
 * DetallePresupuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetallePresupuestoRepository extends \Doctrine\ORM\EntityRepository
{
}
