<?php

namespace AppBundle\Repository;

/**
 * DetalleRemitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleRemitoRepository extends \Doctrine\ORM\EntityRepository
{
}
