<?php

namespace AppBundle\Repository;

/**
 * DetalleComprobanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleComprobanteRepository extends \Doctrine\ORM\EntityRepository
{
}
