<?php

namespace AppBundle\Repository;

/**
 * DetalleTransferenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleTransferenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
