<?php

namespace AppBundle\Repository;

/**
 * DetalleRevisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleRevisionRepository extends \Doctrine\ORM\EntityRepository
{
}
