<?php

namespace AppBundle\Repository;

/**
 * DetalleChequeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleChequeRepository extends \Doctrine\ORM\EntityRepository
{
}
