<?php

namespace AppBundle\Repository;

/**
 * EstadoPedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoPedidoRepository extends \Doctrine\ORM\EntityRepository
{
}
