<?php

namespace AppBundle\Repository;

/**
 * EstadoRevisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoRevisionRepository extends \Doctrine\ORM\EntityRepository
{
}
