<?php

namespace AppBundle\Repository;

/**
 * InmuebleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InmuebleRepository extends \Doctrine\ORM\EntityRepository
{
}
