<?php

namespace AppBundle\Repository;

/**
 * MedioPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedioPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
