<?php

namespace AppBundle\Repository;

/**
 * ModoPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModoPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
