<?php

namespace AppBundle\Repository;

/**
 * ObraFinalizacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObraFinalizacionRepository extends \Doctrine\ORM\EntityRepository
{
}
