<?php

namespace AppBundle\Repository;

/**
 * PagoMedioPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagoMedioPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
