<?php

namespace AppBundle\Repository;

/**
 * PrecioSitioTareaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrecioSitioTareaRepository extends \Doctrine\ORM\EntityRepository
{
}
