<?php

namespace AppBundle\Repository;

/**
 * PresupuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresupuestoRepository extends \Doctrine\ORM\EntityRepository
{
}
