<?php

namespace AppBundle\Repository;

/**
 * SalidaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SalidaRepository extends \Doctrine\ORM\EntityRepository
{
}
