<?php

namespace AppBundle\Repository;

/**
 * SitioTareaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SitioTareaRepository extends \Doctrine\ORM\EntityRepository
{
}
