<?php

namespace AppBundle\Repository;

/**
 * TipoRevisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoRevisionRepository extends \Doctrine\ORM\EntityRepository
{
}
