<?php

namespace AppBundle\Repository;

/**
 * TipoInmuebleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoInmuebleRepository extends \Doctrine\ORM\EntityRepository
{
}
